name: Build Folia JAR
on: [push, pull_request]
permissions:
  actions: read
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gradle/actions/wrapper-validation@main
      - uses: gradle/actions/setup-gradle@main
      - uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - run: ./gradlew applyPatches
      - run: ./gradlew createMojmapPaperclipJar
      - uses: softprops/action-gh-release@master
        with:
          tag_name: Game of Life Folia v${{github.run_number}}
          files: Folia/build/libs/*.jar
